# SPDX-FileCopyrightText: Tobias Knöppler <thecalcaholic@web.de>
# SPDX-License-Identifier: AGPL-3.0-or-later

name: Release

on:
  push:
    tags:
      - "v*"
      - "test*"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        path: secrets

    - name: Read package.json node and npm engines version
      uses: skjnldsv/read-package-engines-version-actions@v1.2
      id: versions
      with:
        fallbackNode: '^12'
        fallbackNpm: '^6'
        path: './secrets'

    - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ steps.versions.outputs.nodeVersion }}

    - name: Build app
      run: |
        npm install --dev
        make build
      working-directory: ./secrets

    - name: "Create release"
      run: |
        set -x
        make build
        mkdir secrets
        mv appinfo img js lib l10n LICENSES templates LICENSE.md secrets/
        tar -caf secrets.tar.gz secrets
        sha256sum secrets.tar.gz > secrets.sha256
        tag_name="${GITHUB_REF##*/}"
        gh release create -n "${tag_name}" "${tag_name}"
        gh release upload "${tag_name}" secrets.tar.gz
        gh release upload "${tag_name}" secrets.sha256
      working-directory: ./secrets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

